<?php

/**
 * KBSP User management, part of Knowledge base site profile
 * @author  marcus
 *
 * Creates user role "wiki-user"
 *
 * ProcessWire 2.x
 * Copyright (C) 2010 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class KbspUser implements Module {

	public static function getModuleInfo() {
		return array(
			"title" => "KBSP User management, part of Knowledge base site profile",
			"version" => 001,
			"summary" => "Creates user role 'wiki-user'",
			"autoload" => false
		);
	}

	public function init() {}

	public function install() {

		$role = wire("roles")->get("wiki-user");

		if (!$role->id) {
			wire("roles")->add("wiki-user");
		}

	}

}